.\" progman - Copyright 1998-2007 Decklin Foster <decklin@red-bean.com>.
.\" This program is free software; please see LICENSE for details.
.TH "PROGMAN" 1x
.SH "NAME"
progman \- A Window Manager
.SH "SYNOPSIS"
.B progman
.I [options...]
.SH "DESCRIPTION"
.B progman
is an X11 window manager with very few features. It draws a small
titlebar above top-level windows, allows you to manipulate them with the
mouse, and starts other programs when the root window is clicked. That's
also about all it does, so don't expect anything nifty.
.PP
The titlebar contains a small box in the upper right corner. Clicking
the 1st, 2nd, or 3rd buttons on the main area of the titlebar will
raise, move, or lower the window, respectively. Clicking on the box will
respectively hide, resize, or close the window.
.PP
By default, clicking on the root window with button 1 will run
.BR aemenu (1x),
and button 3 will start a new
.BR xterm (1x),
and and button 2 will run
.BR "aemenu \-\-switch" .
.B aemenu
(or another equivalent program) is required to unhide hidden windows;
.B progman
does not do this itself.
.SH "OPTIONS"
.TP
.BI \-\-config \ file\fP, \ \-rc \ file
Read configuration options from
.IR file .
This overrides options which precede it in the command line.
.TP
.BI \-\-font \ xfld\fP, \ \-fn \ xfld
Draw window titles using the font defined by
.IR xfld .
.TP
.BI \-\-bgcolor \ color\fP, \ \-bg \ color
Set the background color of window frames.
.TP
.BI \-\-fgcolor \ color\fP, \ \-fg \ color
Set the foreground color of window frames.
.TP
.BI \-\-bdcolor \ color\fP, \ \-bd \ color
Set the color of window borders.
.TP
.BI \-\-bdwidth \ width\fP, \ \-bw \ width
Draw window borders
.I width
pixels wide.
.TP
.BI \-\-padding \ width\fP, \ \-p \ width
Draw
.I width
pixels of space between window borders and window titles.
.TP
.BI \-\-new1 \ command\fP, \ \-1 \ cmd
Run
.I command
when button 1 is clicked on the root window.
.TP
.BI \-\-new2 \ command\fP, \ \-2 \ cmd
Run
.I command
when button 2 is clicked on the root window.
.TP
.BI \-\-new3 \ command\fP, \ \-3 \ cmd
Run
.I command
when button 3 is clicked on the root window.
.TP
.B \-\-help, \-h
Print a short help message to stdout and exit.
.TP
.B \-\-version, \-v
Print version information to stdout and exit.
.SH "ENVIRONMENT"
.B DISPLAY
Sets which X display will be managed by
.BR progman .
.SH "SEE ALSO"
.BR aeclients (1x),
.BR X (7),
.I The Inter-Client Communication Conventions Manual
(from the X11R6 documentation).
.SH "AUTHOR"
Decklin Foster <decklin@red\-bean.com>
